# Generated by Django 5.2.8 on 2026-05-16 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleAuth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_decription", models.CharField(max_length=255)),
                ("vehicle_registration", models.CharField(max_length=10)),
                ("odometer", models.PositiveIntegerField()),
                ("surname_initials", models.CharField(max_length=255)),
                ("sap_no", models.IntegerField()),
                ("department", models.CharField(max_length=255)),
                ("cost_centre", models.IntegerField()),
                ("Designation", models.CharField(max_length=255)),
                (
                    "SDC",
                    models.CharField(
                        choices=[
                            ("REUVEN", "reuven"),
                            ("ROODEPORT", "roodeport"),
                            ("MIDRAND", "midrand"),
                            ("INNER CITY", "inner city"),
                        ],
                        max_length=10,
                    ),
                ),
                ("resident_address", models.TextField()),
                (
                    "secure_locked_place",
                    models.CharField(
                        choices=[("YES", "yes"), ("NO", "no")], max_length=3
                    ),
                ),
                (
                    "behind_locked_gates",
                    models.CharField(
                        choices=[("YES", "yes"), ("NO", "no")], max_length=3
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("motivation", models.TextField()),
                ("declaration", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SENIOR MANAGER/GM", "senior manager/gm"),
                            ("LINE MANAGER", "line manager"),
                            ("FLEET COMLPLIANCE", "fleet compliance"),
                            ("FLEET MANAGER", "fleet manager"),
                        ],
                        max_length=50,
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True)),
                ("signed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "authorization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="CityPowerVehicle.vehicleauth",
                    ),
                ),
            ],
        ),
    ]
