# Generated by Django 6.0.5 on 2026-05-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CityPowerVehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleauth",
            name="SDC",
            field=models.CharField(
                choices=[
                    ("REUVEN", "reuven"),
                    ("ROODEPORT", "roodeport"),
                    ("MIDRAND", "midrand"),
                    ("INNER CITY", "inner city"),
                    ("SIEMERT", "siemert"),
                    ("LENASIA", "lenasia"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="vehicleauth",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
