# Generated by Django 5.2.14 on 2026-05-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityPowerVehicle', '0002_alter_approval_id_alter_vehicleauth_sdc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicleauth',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
