# Generated by Django 5.2.14 on 2026-05-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityPowerVehicle', '0003_alter_approval_id_alter_vehicleauth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleauth',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleauth',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
