# Generated by Django 5.2.14 on 2026-05-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityPowerVehicle', '0004_alter_vehicleauth_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleauth',
            name='next_approval_role',
            field=models.CharField(choices=[('LINE MANAGER', 'Line Manager'), ('SENIOR MANAGER/GM', 'Senior Manager/GM'), ('FLEET COMLPLIANCE', 'Fleet Compliance'), ('FLEET MANAGER', 'Fleet Manager')], default='LINE MANAGER', max_length=50),
        ),
        migrations.AlterField(
            model_name='approval',
            name='role',
            field=models.CharField(choices=[('LINE MANAGER', 'Line Manager'), ('SENIOR MANAGER/GM', 'Senior Manager/GM'), ('FLEET COMLPLIANCE', 'Fleet Compliance'), ('FLEET MANAGER', 'Fleet Manager')], max_length=50),
        ),
    ]
