# Generated by Django 5.2.14 on 2026-05-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityPowerVehicle', '0005_vehicleauth_next_approval_role_alter_approval_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleauth',
            name='fleet_compliance_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vehicleauth',
            name='fleet_compliance_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicleauth',
            name='fleet_manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vehicleauth',
            name='fleet_manager_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicleauth',
            name='line_manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vehicleauth',
            name='line_manager_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicleauth',
            name='senior_manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vehicleauth',
            name='senior_manager_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
