# Generated by Django 6.0.5 on 2026-07-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CityPowerVehicle", "0008_authorizationaccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="role",
            field=models.CharField(
                choices=[
                    ("LINE MANAGER", "Line Manager"),
                    ("SENIOR MANAGER/GM", "Senior Manager/GM"),
                    ("FLEET COMPLIANCE", "Fleet Compliance"),
                    ("FLEET MANAGER", "Fleet Manager"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="vehicleauth",
            name="next_approval_role",
            field=models.CharField(
                choices=[
                    ("LINE MANAGER", "Line Manager"),
                    ("SENIOR MANAGER/GM", "Senior Manager/GM"),
                    ("FLEET COMPLIANCE", "Fleet Compliance"),
                    ("FLEET MANAGER", "Fleet Manager"),
                ],
                default="LINE MANAGER",
                max_length=50,
            ),
        ),
    ]
